name: quizzler
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  rflutter_alert: ^2.0.7
  #TODO: Step 1 - Add the rFlutter Alert package as a dependency here and use "Packages get".

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
